//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prooffice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbofficeEntities : DbContext
    {
        public dbofficeEntities()
            : base("name=dbofficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcountrymast> tblcountrymasts { get; set; }
        public virtual DbSet<tbloffice> tbloffices { get; set; }
        public virtual DbSet<tblstudentdlt> tblstudentdlts { get; set; }
        public virtual DbSet<tblstudentinfo> tblstudentinfoes { get; set; }
    }
}
