//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prooffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudentinfo
    {
        public System.Guid transid { get; set; }
        public string studentname { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string country { get; set; }
        public string fileupload { get; set; }
    }
}
